import NavLink from "@/components/nav-link";
import Navbar from "@/components/navbar";
import Sidebar from "@/components/sidebar";
import { Metadata } from "next";
import Image from "next/image";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function DashboardLayout({ children }: LayoutProps<"/">) {
  return (
    <>
      <Navbar />
      <section className="grid min-h-screen grid-cols-12">
        <Sidebar />
        <main className="col-span-10 bg-white">{children}</main>
      </section>
    </>
  );
}
